<?php
// ===================================================================================================
//                           _  __     _ _
//                          | |/ /__ _| | |_ _  _ _ _ __ _
//                          | ' </ _` | |  _| || | '_/ _` |
//                          |_|\_\__,_|_|\__|\_,_|_| \__,_|
//
// This file is part of the Kaltura Collaborative Media Suite which allows users
// to do with audio, video, and animation what Wiki platforms allow them to do with
// text.
//
// Copyright (C) 2006-2023  Kaltura Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// @ignore
// ===================================================================================================

/**
 * @package Kaltura
 * @subpackage Client
 */
class Kaltura_Client_Type_CloudUploadSettingsConfiguration extends Kaltura_Client_Type_PartnerConfiguration
{
	public function getKalturaObjectType()
	{
		return 'KalturaCloudUploadSettingsConfiguration';
	}
	
	public function __construct(SimpleXMLElement $xml = null, $jsonObject = null)
	{
		parent::__construct($xml, $jsonObject);
		
		if(!is_null($xml) && !is_null($jsonObject))
			throw new Kaltura_Client_ClientException("construct with either XML or JSON object, not both", Kaltura_Client_ClientException::ERROR_CONSTRUCT_ARGS_CONFLICT);
		
		if(is_null($xml) && is_null($jsonObject))
			return;
		
		if(!is_null($xml) && count($xml->defaultAllowedFileExtensions))
			$this->defaultAllowedFileExtensions = (string)$xml->defaultAllowedFileExtensions;
		if(!is_null($jsonObject) && isset($jsonObject->defaultAllowedFileExtensions))
			$this->defaultAllowedFileExtensions = (string)$jsonObject->defaultAllowedFileExtensions;
		if(!is_null($xml) && count($xml->customAllowedFileExtensions))
			$this->customAllowedFileExtensions = (string)$xml->customAllowedFileExtensions;
		if(!is_null($jsonObject) && isset($jsonObject->customAllowedFileExtensions))
			$this->customAllowedFileExtensions = (string)$jsonObject->customAllowedFileExtensions;
	}
	/**
	 * Comma seperated list of file extensions that allowed to all partners
	 *
	 * @var string
	 * @readonly
	 */
	public $defaultAllowedFileExtensions = null;

	/**
	 * Comma seperated list of file extensions that allowed to partner in question
	 *             {&quot;323&quot;, &quot;text/h323&quot; },
	 *             {&quot;3g2&quot;,&quot;video/3gpp2&quot;},
	 *             { &quot;3gp&quot;,&quot;video/3gpp&quot;},
	 *             { &quot;3gp2&quot;, &quot;video/3gpp2&quot;},
	 *             {&quot;3gpp&quot;,  &quot;video/3gpp&quot;},
	 *             {&quot;7z&quot;,  &quot;application/x-7z-compressed&quot;},
	 *             {&quot;aa&quot;,&quot;audio/audible&quot; },
	 *             {&quot;aac&quot;,&quot;audio/aac&quot;},
	 *             {&quot;aaf&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;aax&quot;,&quot;audio/vnd.audible.aax&quot;},
	 *             {&quot;ac3&quot;,&quot;audio/ac3&quot;},
	 *             {&quot;aca&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;accda&quot;,&quot;application/msaccess.addin&quot;},
	 *             {&quot;accdb&quot;,&quot;application/msaccess&quot;},
	 *             {&quot;accdc&quot;,&quot;application/msaccess.cab&quot;},
	 *             {&quot;accde&quot;,&quot;application/msaccess&quot;},
	 *             {&quot;accdr&quot;,&quot;application/msaccess.runtime&quot;},
	 *             {&quot;accdt&quot;,&quot;application/msaccess&quot;},
	 *             {&quot;accdw&quot;,&quot;application/msaccess.webapplication&quot;},
	 *             {&quot;accft&quot;,&quot;application/msaccess.ftemplate&quot;},
	 *             {&quot;acx&quot;,&quot;application/internet-property-stream&quot;},
	 *             {&quot;addin&quot;,&quot;text/xml&quot;},
	 *             {&quot;ade&quot;,&quot;application/msaccess&quot;},
	 *             {&quot;adobebridge&quot;,&quot;application/x-bridge-url&quot;},
	 *             {&quot;adp&quot;,&quot;application/msaccess&quot;},
	 *             {&quot;adt&quot;,&quot;audio/vnd.dlna.adts&quot;},
	 *             {&quot;adts&quot;,&quot;audio/aac&quot;},
	 *             {&quot;afm&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;ai&quot;,&quot;application/postscript&quot;},
	 *             {&quot;aif&quot;,&quot;audio/x-aiff&quot;},
	 *             {&quot;aifc&quot;,&quot;audio/aiff&quot;},
	 *             {&quot;aiff&quot;,&quot;audio/aiff&quot;},
	 *             {&quot;air&quot;,&quot;application/vnd.adobe.air-application-installer-package+zip&quot;},
	 *             {&quot;amc&quot;,&quot;application/x-mpeg&quot;},
	 *             {&quot;application&quot;,&quot;application/x-ms-application&quot;},
	 *             {&quot;art&quot;,&quot;image/x-jg&quot;},
	 *             {&quot;asa&quot;,&quot;application/xml&quot;},
	 *             {&quot;asax&quot;,&quot;application/xml&quot;},
	 *             {&quot;ascx&quot;,&quot;application/xml&quot;},
	 *             {&quot;asd&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;asf&quot;,&quot;video/x-ms-asf&quot;},
	 *             {&quot;ashx&quot;,&quot;application/xml&quot;},
	 *             {&quot;asi&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;asm&quot;,&quot;text/plain&quot;},
	 *             {&quot;asmx&quot;,&quot;application/xml&quot;},
	 *             {&quot;aspx&quot;,&quot;application/xml&quot;},
	 *             {&quot;asr&quot;,&quot;video/x-ms-asf&quot;},
	 *             {&quot;asx&quot;,&quot;video/x-ms-asf&quot;},
	 *             {&quot;atom&quot;,&quot;application/atom+xml&quot;},
	 *             {&quot;au&quot;,&quot;audio/basic&quot;},
	 *             {&quot;avi&quot;,&quot;video/x-msvideo&quot;},
	 *             {&quot;axs&quot;,&quot;application/olescript&quot;},
	 *             {&quot;bas&quot;,&quot;text/plain&quot;},
	 *             {&quot;bcpio&quot;,&quot;application/x-bcpio&quot;},
	 *             {&quot;bin&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;bmp&quot;,&quot;image/bmp&quot;},
	 *             {&quot;c&quot;,&quot;text/plain&quot;},
	 *             {&quot;cab&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;caf&quot;,&quot;audio/x-caf&quot;},
	 *             {&quot;calx&quot;,&quot;application/vnd.ms-office.calx&quot;},
	 *             {&quot;cat&quot;,&quot;application/vnd.ms-pki.seccat&quot;},
	 *             {&quot;cc&quot;,&quot;text/plain&quot;},
	 *             {&quot;cd&quot;,&quot;text/plain&quot;},
	 *             {&quot;cdda&quot;,&quot;audio/aiff&quot;},
	 *             {&quot;cdf&quot;,&quot;application/x-cdf&quot;},
	 *             {&quot;cer&quot;,&quot;application/x-x509-ca-cert&quot;},
	 *             {&quot;chm&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;class&quot;,&quot;application/x-java-applet&quot;},
	 *             {&quot;clp&quot;,&quot;application/x-msclip&quot;},
	 *             {&quot;cmx&quot;,&quot;image/x-cmx&quot;},
	 *             {&quot;cnf&quot;,&quot;text/plain&quot;},
	 *             {&quot;cod&quot;,&quot;image/cis-cod&quot;},
	 *             {&quot;config&quot;,&quot;application/xml&quot;},
	 *             {&quot;contact&quot;,&quot;text/x-ms-contact&quot;},
	 *             {&quot;coverage&quot;,&quot;application/xml&quot;},
	 *             {&quot;cpio&quot;,&quot;application/x-cpio&quot;},
	 *             {&quot;cpp&quot;,&quot;text/plain&quot;},
	 *             {&quot;crd&quot;,&quot;application/x-mscardfile&quot;},
	 *             {&quot;crl&quot;,&quot;application/pkix-crl&quot;},
	 *             {&quot;crt&quot;,&quot;application/x-x509-ca-cert&quot;},
	 *             {&quot;cs&quot;,&quot;text/plain&quot;},
	 *             {&quot;csdproj&quot;,&quot;text/plain&quot;},
	 *             {&quot;csh&quot;,&quot;application/x-csh&quot;},
	 *             {&quot;csproj&quot;,&quot;text/plain&quot;},
	 *             {&quot;css&quot;,&quot;text/css&quot;},
	 *             {&quot;csv&quot;,&quot;text/csv&quot;},
	 *             {&quot;cur&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;cxx&quot;,&quot;text/plain&quot;},
	 *             {&quot;dat&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;datasource&quot;,&quot;application/xml&quot;},
	 *             {&quot;dbproj&quot;,&quot;text/plain&quot;},
	 *             {&quot;dcr&quot;,&quot;application/x-director&quot;},
	 *             {&quot;def&quot;,&quot;text/plain&quot;},
	 *             {&quot;deploy&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;der&quot;,&quot;application/x-x509-ca-cert&quot;},
	 *             {&quot;dgml&quot;,&quot;application/xml&quot;},
	 *             {&quot;dib&quot;,&quot;image/bmp&quot;},
	 *             {&quot;dif&quot;,&quot;video/x-dv&quot;},
	 *             {&quot;dir&quot;,&quot;application/x-director&quot;},
	 *             {&quot;disco&quot;,&quot;text/xml&quot;},
	 *             {&quot;dll&quot;,&quot;application/x-msdownload&quot;},
	 *             {&quot;dll.config&quot;,&quot;text/xml&quot;},
	 *             {&quot;dlm&quot;,&quot;text/dlm&quot;},
	 *             {&quot;doc&quot;,&quot;application/msword&quot;},
	 *             {&quot;docm&quot;,&quot;application/vnd.ms-word.document.macroenabled.12&quot;},
	 *             {&quot;docx&quot;,&quot;application/vnd.openxmlformats-officedocument.wordprocessingml.document&quot;},
	 *             {&quot;dot&quot;,&quot;application/msword&quot;},
	 *             {&quot;dotm&quot;,&quot;application/vnd.ms-word.template.macroenabled.12&quot;},
	 *             {&quot;dotx&quot;,&quot;application/vnd.openxmlformats-officedocument.wordprocessingml.template&quot;},
	 *             {&quot;dsp&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;dsw&quot;,&quot;text/plain&quot;},
	 *             {&quot;dtd&quot;,&quot;text/xml&quot;},
	 *             {&quot;dtsconfig&quot;,&quot;text/xml&quot;},
	 *             {&quot;dv&quot;,&quot;video/x-dv&quot;},
	 *             {&quot;dvi&quot;,&quot;application/x-dvi&quot;},
	 *             {&quot;dwf&quot;,&quot;drawing/x-dwf&quot;},
	 *             {&quot;dwp&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;dxr&quot;,&quot;application/x-director&quot;},
	 *             {&quot;eml&quot;,&quot;message/rfc822&quot;},
	 *             {&quot;emz&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;eot&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;eps&quot;,&quot;application/postscript&quot;},
	 *             {&quot;etl&quot;,&quot;application/etl&quot;},
	 *             {&quot;etx&quot;,&quot;text/x-setext&quot;},
	 *             {&quot;evy&quot;,&quot;application/envoy&quot;},
	 *             {&quot;exe&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;exe.config&quot;,&quot;text/xml&quot;},
	 *             {&quot;fdf&quot;,&quot;application/vnd.fdf&quot;},
	 *             {&quot;fif&quot;,&quot;application/fractals&quot;},
	 *             {&quot;filters&quot;,&quot;application/xml&quot;},
	 *             {&quot;fla&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;flr&quot;,&quot;x-world/x-vrml&quot;},
	 *             {&quot;flv&quot;,&quot;video/x-flv&quot;},
	 *             {&quot;fsscript&quot;,&quot;application/fsharp-script&quot;},
	 *             {&quot;fsx&quot;,&quot;application/fsharp-script&quot;},
	 *             {&quot;generictest&quot;,&quot;application/xml&quot;},
	 *             {&quot;gif&quot;,&quot;image/gif&quot;},
	 *             {&quot;group&quot;,&quot;text/x-ms-group&quot;},
	 *             {&quot;gsm&quot;,&quot;audio/x-gsm&quot;},
	 *             {&quot;gtar&quot;,&quot;application/x-gtar&quot;},
	 *             {&quot;gz&quot;,&quot;application/x-gzip&quot;},
	 *             {&quot;h&quot;,&quot;text/plain&quot;},
	 *             {&quot;hdf&quot;,&quot;application/x-hdf&quot;},
	 *             {&quot;hdml&quot;,&quot;text/x-hdml&quot;},
	 *             {&quot;hhc&quot;,&quot;application/x-oleobject&quot;},
	 *             {&quot;hhk&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;hhp&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;hlp&quot;,&quot;application/winhlp&quot;},
	 *             {&quot;hpp&quot;,&quot;text/plain&quot;},
	 *             {&quot;hqx&quot;,&quot;application/mac-binhex40&quot;},
	 *             {&quot;hta&quot;,&quot;application/hta&quot;},
	 *             {&quot;htc&quot;,&quot;text/x-component&quot;},
	 *             {&quot;htm&quot;,&quot;text/html&quot;},
	 *             {&quot;html&quot;,&quot;text/html&quot;},
	 *             {&quot;htt&quot;,&quot;text/webviewhtml&quot;},
	 *             {&quot;hxa&quot;,&quot;application/xml&quot;},
	 *             {&quot;hxc&quot;,&quot;application/xml&quot;},
	 *             {&quot;hxd&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;hxe&quot;,&quot;application/xml&quot;},
	 *             {&quot;hxf&quot;,&quot;application/xml&quot;},
	 *             {&quot;hxh&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;hxi&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;hxk&quot;,&quot;application/xml&quot;},
	 *             {&quot;hxq&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;hxr&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;hxs&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;hxt&quot;,&quot;text/html&quot;},
	 *             {&quot;hxv&quot;,&quot;application/xml&quot;},
	 *             {&quot;hxw&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;hxx&quot;,&quot;text/plain&quot;},
	 *             {&quot;i&quot;,&quot;text/plain&quot;},
	 *             {&quot;ico&quot;,&quot;image/x-icon&quot;},
	 *             {&quot;ics&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;idl&quot;,&quot;text/plain&quot;},
	 *             {&quot;ief&quot;,&quot;image/ief&quot;},
	 *             {&quot;iii&quot;,&quot;application/x-iphone&quot;},
	 *             {&quot;inc&quot;,&quot;text/plain&quot;},
	 *             {&quot;inf&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;inl&quot;,&quot;text/plain&quot;},
	 *             {&quot;ins&quot;,&quot;application/x-internet-signup&quot;},
	 *             {&quot;ipa&quot;,&quot;application/x-itunes-ipa&quot;},
	 *             {&quot;ipg&quot;,&quot;application/x-itunes-ipg&quot;},
	 *             {&quot;ipproj&quot;,&quot;text/plain&quot;},
	 *             {&quot;ipsw&quot;,&quot;application/x-itunes-ipsw&quot;},
	 *             {&quot;iqy&quot;,&quot;text/x-ms-iqy&quot;},
	 *             {&quot;isp&quot;,&quot;application/x-internet-signup&quot;},
	 *             {&quot;ite&quot;,&quot;application/x-itunes-ite&quot;},
	 *             {&quot;itlp&quot;,&quot;application/x-itunes-itlp&quot;},
	 *             {&quot;itms&quot;,&quot;application/x-itunes-itms&quot;},
	 *             {&quot;itpc&quot;,&quot;application/x-itunes-itpc&quot;},
	 *             {&quot;ivf&quot;,&quot;video/x-ivf&quot;},
	 *             {&quot;jar&quot;,&quot;application/java-archive&quot;},
	 *             {&quot;java&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;jck&quot;,&quot;application/liquidmotion&quot;},
	 *             {&quot;jcz&quot;,&quot;application/liquidmotion&quot;},
	 *             {&quot;jfif&quot;,&quot;image/pjpeg&quot;},
	 *             {&quot;jnlp&quot;,&quot;application/x-java-jnlp-file&quot;},
	 *             {&quot;jpb&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;jpe&quot;,&quot;image/jpeg&quot;},
	 *             {&quot;jpeg&quot;,&quot;image/jpeg&quot;},
	 *             {&quot;jpg&quot;,&quot;image/jpeg&quot;},
	 *             {&quot;js&quot;,&quot;application/x-javascript&quot;},
	 *             {&quot;jsx&quot;,&quot;text/jscript&quot;},
	 *             {&quot;jsxbin&quot;,&quot;text/plain&quot;},
	 *             {&quot;latex&quot;,&quot;application/x-latex&quot;},
	 *             {&quot;library-ms&quot;,&quot;application/windows-library+xml&quot;},
	 *             {&quot;lit&quot;,&quot;application/x-ms-reader&quot;},
	 *             {&quot;loadtest&quot;,&quot;application/xml&quot;},
	 *             {&quot;lpk&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;lsf&quot;,&quot;video/x-la-asf&quot;},
	 *             {&quot;lst&quot;,&quot;text/plain&quot;},
	 *             {&quot;lsx&quot;,&quot;video/x-la-asf&quot;},
	 *             {&quot;lzh&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;m13&quot;,&quot;application/x-msmediaview&quot;},
	 *             {&quot;m14&quot;,&quot;application/x-msmediaview&quot;},
	 *             {&quot;m1v&quot;,&quot;video/mpeg&quot;},
	 *             {&quot;m2t&quot;,&quot;video/vnd.dlna.mpeg-tts&quot;},
	 *             {&quot;m2ts&quot;,&quot;video/vnd.dlna.mpeg-tts&quot;},
	 *             {&quot;m2v&quot;,&quot;video/mpeg&quot;},
	 *             {&quot;m3u&quot;,&quot;audio/x-mpegurl&quot;},
	 *             {&quot;m3u8&quot;,&quot;audio/x-mpegurl&quot;},
	 *             {&quot;m4a&quot;,&quot;audio/m4a&quot;},
	 *             {&quot;m4b&quot;,&quot;audio/m4b&quot;},
	 *             {&quot;m4p&quot;,&quot;audio/m4p&quot;},
	 *             {&quot;m4r&quot;,&quot;audio/x-m4r&quot;},
	 *             {&quot;m4v&quot;,&quot;video/x-m4v&quot;},
	 *             {&quot;mac&quot;,&quot;image/x-macpaint&quot;},
	 *             {&quot;mak&quot;,&quot;text/plain&quot;},
	 *             {&quot;man&quot;,&quot;application/x-troff-man&quot;},
	 *             {&quot;manifest&quot;,&quot;application/x-ms-manifest&quot;},
	 *             {&quot;map&quot;,&quot;text/plain&quot;},
	 *             {&quot;master&quot;,&quot;application/xml&quot;},
	 *             {&quot;mda&quot;,&quot;application/msaccess&quot;},
	 *             {&quot;mdb&quot;,&quot;application/x-msaccess&quot;},
	 *             {&quot;mde&quot;,&quot;application/msaccess&quot;},
	 *             {&quot;mdp&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;me&quot;,&quot;application/x-troff-me&quot;},
	 *             {&quot;mfp&quot;,&quot;application/x-shockwave-flash&quot;},
	 *             {&quot;mht&quot;,&quot;message/rfc822&quot;},
	 *             {&quot;mhtml&quot;,&quot;message/rfc822&quot;},
	 *             {&quot;mid&quot;,&quot;audio/mid&quot;},
	 *             {&quot;midi&quot;,&quot;audio/mid&quot;},
	 *             {&quot;mix&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;mk&quot;,&quot;text/plain&quot;},
	 *             {&quot;mmf&quot;,&quot;application/x-smaf&quot;},
	 *             {&quot;mno&quot;,&quot;text/xml&quot;},
	 *             {&quot;mny&quot;,&quot;application/x-msmoney&quot;},
	 *             {&quot;mod&quot;,&quot;video/mpeg&quot;},
	 *             {&quot;mov&quot;,&quot;video/quicktime&quot;},
	 *             {&quot;movie&quot;,&quot;video/x-sgi-movie&quot;},
	 *             {&quot;mp2&quot;,&quot;video/mpeg&quot;},
	 *             {&quot;mp2v&quot;,&quot;video/mpeg&quot;},
	 *             {&quot;mp3&quot;,&quot;audio/mpeg&quot;},
	 *             {&quot;mp4&quot;,&quot;video/mp4&quot;},
	 *             {&quot;mp4v&quot;,&quot;video/mp4&quot;},
	 *             {&quot;mpa&quot;,&quot;video/mpeg&quot;},
	 *             {&quot;mpe&quot;,&quot;video/mpeg&quot;},
	 *             {&quot;mpeg&quot;,&quot;video/mpeg&quot;},
	 *             {&quot;mpf&quot;,&quot;application/vnd.ms-mediapackage&quot;},
	 *             {&quot;mpg&quot;,&quot;video/mpeg&quot;},
	 *             {&quot;mpp&quot;,&quot;application/vnd.ms-project&quot;},
	 *             {&quot;mpv2&quot;,&quot;video/mpeg&quot;},
	 *             {&quot;mqv&quot;,&quot;video/quicktime&quot;},
	 *             {&quot;ms&quot;,&quot;application/x-troff-ms&quot;},
	 *             {&quot;msi&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;mso&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;mts&quot;,&quot;video/vnd.dlna.mpeg-tts&quot;},
	 *             {&quot;mtx&quot;,&quot;application/xml&quot;},
	 *             {&quot;mvb&quot;,&quot;application/x-msmediaview&quot;},
	 *             {&quot;mvc&quot;,&quot;application/x-miva-compiled&quot;},
	 *             {&quot;mxp&quot;,&quot;application/x-mmxp&quot;},
	 *             {&quot;nc&quot;,&quot;application/x-netcdf&quot;},
	 *             {&quot;nsc&quot;,&quot;video/x-ms-asf&quot;},
	 *             {&quot;nws&quot;,&quot;message/rfc822&quot;},
	 *             {&quot;ocx&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;oda&quot;,&quot;application/oda&quot;},
	 *             {&quot;odc&quot;,&quot;text/x-ms-odc&quot;},
	 *             {&quot;odh&quot;,&quot;text/plain&quot;},
	 *             {&quot;odl&quot;,&quot;text/plain&quot;},
	 *             {&quot;odp&quot;,&quot;application/vnd.oasis.opendocument.presentation&quot;},
	 *             {&quot;ods&quot;,&quot;application/oleobject&quot;},
	 *             {&quot;odt&quot;,&quot;application/vnd.oasis.opendocument.text&quot;},
	 *             {&quot;one&quot;,&quot;application/onenote&quot;},
	 *             {&quot;onea&quot;,&quot;application/onenote&quot;},
	 *             {&quot;onepkg&quot;,&quot;application/onenote&quot;},
	 *             {&quot;onetmp&quot;,&quot;application/onenote&quot;},
	 *             {&quot;onetoc&quot;,&quot;application/onenote&quot;},
	 *             {&quot;onetoc2&quot;,&quot;application/onenote&quot;},
	 *             {&quot;orderedtest&quot;,&quot;application/xml&quot;},
	 *             {&quot;osdx&quot;,&quot;application/opensearchdescription+xml&quot;},
	 *             {&quot;p10&quot;,&quot;application/pkcs10&quot;},
	 *             {&quot;p12&quot;,&quot;application/x-pkcs12&quot;},
	 *             {&quot;p7b&quot;,&quot;application/x-pkcs7-certificates&quot;},
	 *             {&quot;p7c&quot;,&quot;application/pkcs7-mime&quot;},
	 *             {&quot;p7m&quot;,&quot;application/pkcs7-mime&quot;},
	 *             {&quot;p7r&quot;,&quot;application/x-pkcs7-certreqresp&quot;},
	 *             {&quot;p7s&quot;,&quot;application/pkcs7-signature&quot;},
	 *             {&quot;pbm&quot;,&quot;image/x-portable-bitmap&quot;},
	 *             {&quot;pcast&quot;,&quot;application/x-podcast&quot;},
	 *             {&quot;pct&quot;,&quot;image/pict&quot;},
	 *             {&quot;pcx&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;pcz&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;pdf&quot;,&quot;application/pdf&quot;},
	 *             {&quot;pfb&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;pfm&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;pfx&quot;,&quot;application/x-pkcs12&quot;},
	 *             {&quot;pgm&quot;,&quot;image/x-portable-graymap&quot;},
	 *             {&quot;pic&quot;,&quot;image/pict&quot;},
	 *             {&quot;pict&quot;,&quot;image/pict&quot;},
	 *             {&quot;pkgdef&quot;,&quot;text/plain&quot;},
	 *             {&quot;pkgundef&quot;,&quot;text/plain&quot;},
	 *             {&quot;pko&quot;,&quot;application/vnd.ms-pki.pko&quot;},
	 *             {&quot;pls&quot;,&quot;audio/scpls&quot;},
	 *             {&quot;pma&quot;,&quot;application/x-perfmon&quot;},
	 *             {&quot;pmc&quot;,&quot;application/x-perfmon&quot;},
	 *             {&quot;pml&quot;,&quot;application/x-perfmon&quot;},
	 *             {&quot;pmr&quot;,&quot;application/x-perfmon&quot;},
	 *             {&quot;pmw&quot;,&quot;application/x-perfmon&quot;},
	 *             {&quot;png&quot;,&quot;image/png&quot;},
	 *             {&quot;pnm&quot;,&quot;image/x-portable-anymap&quot;},
	 *             {&quot;pnt&quot;,&quot;image/x-macpaint&quot;},
	 *             {&quot;pntg&quot;,&quot;image/x-macpaint&quot;},
	 *             {&quot;pnz&quot;,&quot;image/png&quot;},
	 *             {&quot;pot&quot;,&quot;application/vnd.ms-powerpoint&quot;},
	 *             {&quot;potm&quot;,&quot;application/vnd.ms-powerpoint.template.macroenabled.12&quot;},
	 *             {&quot;potx&quot;,&quot;application/vnd.openxmlformats-officedocument.presentationml.template&quot;},
	 *             {&quot;ppa&quot;,&quot;application/vnd.ms-powerpoint&quot;},
	 *             {&quot;ppam&quot;,&quot;application/vnd.ms-powerpoint.addin.macroenabled.12&quot;},
	 *             {&quot;ppm&quot;,&quot;image/x-portable-pixmap&quot;},
	 *             {&quot;pps&quot;,&quot;application/vnd.ms-powerpoint&quot;},
	 *             {&quot;ppsm&quot;,&quot;application/vnd.ms-powerpoint.slideshow.macroenabled.12&quot;},
	 *             {&quot;ppsx&quot;,&quot;application/vnd.openxmlformats-officedocument.presentationml.slideshow&quot;},
	 *             {&quot;ppt&quot;,&quot;application/vnd.ms-powerpoint&quot;},
	 *             {&quot;pptm&quot;,&quot;application/vnd.ms-powerpoint.presentation.macroenabled.12&quot;},
	 *             {&quot;pptx&quot;,&quot;application/vnd.openxmlformats-officedocument.presentationml.presentation&quot;},
	 *             {&quot;prf&quot;,&quot;application/pics-rules&quot;},
	 *             {&quot;prm&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;prx&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;ps&quot;,&quot;application/postscript&quot;},
	 *             {&quot;psc1&quot;,&quot;application/powershell&quot;},
	 *             {&quot;psd&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;psess&quot;,&quot;application/xml&quot;},
	 *             {&quot;psm&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;psp&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;pub&quot;,&quot;application/x-mspublisher&quot;},
	 *             {&quot;pwz&quot;,&quot;application/vnd.ms-powerpoint&quot;},
	 *             {&quot;qht&quot;,&quot;text/x-html-insertion&quot;},
	 *             {&quot;qhtm&quot;,&quot;text/x-html-insertion&quot;},
	 *             {&quot;qt&quot;,&quot;video/quicktime&quot;},
	 *             {&quot;qti&quot;,&quot;image/x-quicktime&quot;},
	 *             {&quot;qtif&quot;,&quot;image/x-quicktime&quot;},
	 *             {&quot;qtl&quot;,&quot;application/x-quicktimeplayer&quot;},
	 *             {&quot;qxd&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;ra&quot;,&quot;audio/x-pn-realaudio&quot;},
	 *             {&quot;ram&quot;,&quot;audio/x-pn-realaudio&quot;},
	 *             {&quot;rar&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;ras&quot;,&quot;image/x-cmu-raster&quot;},
	 *             {&quot;rat&quot;,&quot;application/rat-file&quot;},
	 *             {&quot;rc&quot;,&quot;text/plain&quot;},
	 *             {&quot;rc2&quot;,&quot;text/plain&quot;},
	 *             {&quot;rct&quot;,&quot;text/plain&quot;},
	 *             {&quot;rdlc&quot;,&quot;application/xml&quot;},
	 *             {&quot;resx&quot;,&quot;application/xml&quot;},
	 *             {&quot;rf&quot;,&quot;image/vnd.rn-realflash&quot;},
	 *             {&quot;rgb&quot;,&quot;image/x-rgb&quot;},
	 *             {&quot;rgs&quot;,&quot;text/plain&quot;},
	 *             {&quot;rm&quot;,&quot;application/vnd.rn-realmedia&quot;},
	 *             {&quot;rmi&quot;,&quot;audio/mid&quot;},
	 *             {&quot;rmp&quot;,&quot;application/vnd.rn-rn_music_package&quot;},
	 *             {&quot;roff&quot;,&quot;application/x-troff&quot;},
	 *             {&quot;rpm&quot;,&quot;audio/x-pn-realaudio-plugin&quot;},
	 *             {&quot;rqy&quot;,&quot;text/x-ms-rqy&quot;},
	 *             {&quot;rtf&quot;,&quot;application/rtf&quot;},
	 *             {&quot;rtx&quot;,&quot;text/richtext&quot;},
	 *             {&quot;ruleset&quot;,&quot;application/xml&quot;},
	 *             {&quot;s&quot;,&quot;text/plain&quot;},
	 *             {&quot;safariextz&quot;,&quot;application/x-safari-safariextz&quot;},
	 *             {&quot;scd&quot;,&quot;application/x-msschedule&quot;},
	 *             {&quot;sct&quot;,&quot;text/scriptlet&quot;},
	 *             {&quot;sd2&quot;,&quot;audio/x-sd2&quot;},
	 *             {&quot;sdp&quot;,&quot;application/sdp&quot;},
	 *             {&quot;sea&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;searchconnector-ms&quot;,&quot;application/windows-search-connector+xml&quot;},
	 *             {&quot;setpay&quot;,&quot;application/set-payment-initiation&quot;},
	 *             {&quot;setreg&quot;,&quot;application/set-registration-initiation&quot;},
	 *             {&quot;settings&quot;,&quot;application/xml&quot;},
	 *             {&quot;sgimb&quot;,&quot;application/x-sgimb&quot;},
	 *             {&quot;sgml&quot;,&quot;text/sgml&quot;},
	 *             {&quot;sh&quot;,&quot;application/x-sh&quot;},
	 *             {&quot;shar&quot;,&quot;application/x-shar&quot;},
	 *             {&quot;shtml&quot;,&quot;text/html&quot;},
	 *             {&quot;sit&quot;,&quot;application/x-stuffit&quot;},
	 *             {&quot;sitemap&quot;,&quot;application/xml&quot;},
	 *             {&quot;skin&quot;,&quot;application/xml&quot;},
	 *             {&quot;sldm&quot;,&quot;application/vnd.ms-powerpoint.slide.macroenabled.12&quot;},
	 *             {&quot;sldx&quot;,&quot;application/vnd.openxmlformats-officedocument.presentationml.slide&quot;},
	 *             {&quot;slk&quot;,&quot;application/vnd.ms-excel&quot;},
	 *             {&quot;sln&quot;,&quot;text/plain&quot;},
	 *             {&quot;slupkg-ms&quot;,&quot;application/x-ms-license&quot;},
	 *             {&quot;smd&quot;,&quot;audio/x-smd&quot;},
	 *             {&quot;smi&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;smx&quot;,&quot;audio/x-smd&quot;},
	 *             {&quot;smz&quot;,&quot;audio/x-smd&quot;},
	 *             {&quot;snd&quot;,&quot;audio/basic&quot;},
	 *             {&quot;snippet&quot;,&quot;application/xml&quot;},
	 *             {&quot;snp&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;sol&quot;,&quot;text/plain&quot;},
	 *             {&quot;sor&quot;,&quot;text/plain&quot;},
	 *             {&quot;spc&quot;,&quot;application/x-pkcs7-certificates&quot;},
	 *             {&quot;spl&quot;,&quot;application/futuresplash&quot;},
	 *             {&quot;src&quot;,&quot;application/x-wais-source&quot;},
	 *             {&quot;srf&quot;,&quot;text/plain&quot;},
	 *             {&quot;ssisdeploymentmanifest&quot;,&quot;text/xml&quot;},
	 *             {&quot;ssm&quot;,&quot;application/streamingmedia&quot;},
	 *             {&quot;sst&quot;,&quot;application/vnd.ms-pki.certstore&quot;},
	 *             {&quot;stl&quot;,&quot;application/vnd.ms-pki.stl&quot;},
	 *             {&quot;sv4cpio&quot;,&quot;application/x-sv4cpio&quot;},
	 *             {&quot;sv4crc&quot;,&quot;application/x-sv4crc&quot;},
	 *             {&quot;svc&quot;,&quot;application/xml&quot;},
	 *             {&quot;swf&quot;,&quot;application/x-shockwave-flash&quot;},
	 *             {&quot;t&quot;,&quot;application/x-troff&quot;},
	 *             {&quot;tar&quot;,&quot;application/x-tar&quot;},
	 *             {&quot;tcl&quot;,&quot;application/x-tcl&quot;},
	 *             {&quot;testrunconfig&quot;,&quot;application/xml&quot;},
	 *             {&quot;testsettings&quot;,&quot;application/xml&quot;},
	 *             {&quot;tex&quot;,&quot;application/x-tex&quot;},
	 *             {&quot;texi&quot;,&quot;application/x-texinfo&quot;},
	 *             {&quot;texinfo&quot;,&quot;application/x-texinfo&quot;},
	 *             {&quot;tgz&quot;,&quot;application/x-compressed&quot;},
	 *             {&quot;thmx&quot;,&quot;application/vnd.ms-officetheme&quot;},
	 *             {&quot;thn&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;tif&quot;,&quot;image/tiff&quot;},
	 *             {&quot;tiff&quot;,&quot;image/tiff&quot;},
	 *             {&quot;tlh&quot;,&quot;text/plain&quot;},
	 *             {&quot;tli&quot;,&quot;text/plain&quot;},
	 *             {&quot;toc&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;tr&quot;,&quot;application/x-troff&quot;},
	 *             {&quot;trm&quot;,&quot;application/x-msterminal&quot;},
	 *             {&quot;trx&quot;,&quot;application/xml&quot;},
	 *             {&quot;ts&quot;,&quot;video/vnd.dlna.mpeg-tts&quot;},
	 *             {&quot;tsv&quot;,&quot;text/tab-separated-values&quot;},
	 *             {&quot;ttf&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;tts&quot;,&quot;video/vnd.dlna.mpeg-tts&quot;},
	 *             {&quot;txt&quot;,&quot;text/plain&quot;},
	 *             {&quot;u32&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;uls&quot;,&quot;text/iuls&quot;},
	 *             {&quot;user&quot;,&quot;text/plain&quot;},
	 *             {&quot;ustar&quot;,&quot;application/x-ustar&quot;},
	 *             {&quot;vb&quot;,&quot;text/plain&quot;},
	 *             {&quot;vbdproj&quot;,&quot;text/plain&quot;},
	 *             {&quot;vbk&quot;,&quot;video/mpeg&quot;},
	 *             {&quot;vbproj&quot;,&quot;text/plain&quot;},
	 *             {&quot;vbs&quot;,&quot;text/vbscript&quot;},
	 *             {&quot;vcf&quot;,&quot;text/x-vcard&quot;},
	 *             {&quot;vcproj&quot;,&quot;application/xml&quot;},
	 *             {&quot;vcs&quot;,&quot;text/plain&quot;},
	 *             {&quot;vcxproj&quot;,&quot;application/xml&quot;},
	 *             {&quot;vddproj&quot;,&quot;text/plain&quot;},
	 *             {&quot;vdp&quot;,&quot;text/plain&quot;},
	 *             {&quot;vdproj&quot;,&quot;text/plain&quot;},
	 *             {&quot;vdx&quot;,&quot;application/vnd.ms-visio.viewer&quot;},
	 *             {&quot;vml&quot;,&quot;text/xml&quot;},
	 *             {&quot;vscontent&quot;,&quot;application/xml&quot;},
	 *             {&quot;vsct&quot;,&quot;text/xml&quot;},
	 *             {&quot;vsd&quot;,&quot;application/vnd.visio&quot;},
	 *             {&quot;vsi&quot;,&quot;application/ms-vsi&quot;},
	 *             {&quot;vsix&quot;,&quot;application/vsix&quot;},
	 *             {&quot;vsixlangpack&quot;,&quot;text/xml&quot;},
	 *             {&quot;vsixmanifest&quot;,&quot;text/xml&quot;},
	 *             {&quot;vsmdi&quot;,&quot;application/xml&quot;},
	 *             {&quot;vspscc&quot;,&quot;text/plain&quot;},
	 *             {&quot;vss&quot;,&quot;application/vnd.visio&quot;},
	 *             {&quot;vsscc&quot;,&quot;text/plain&quot;},
	 *             {&quot;vssettings&quot;,&quot;text/xml&quot;},
	 *             {&quot;vssscc&quot;,&quot;text/plain&quot;},
	 *             {&quot;vst&quot;,&quot;application/vnd.visio&quot;},
	 *             {&quot;vstemplate&quot;,&quot;text/xml&quot;},
	 *             {&quot;vsto&quot;,&quot;application/x-ms-vsto&quot;},
	 *             {&quot;vsw&quot;,&quot;application/vnd.visio&quot;},
	 *             {&quot;vsx&quot;,&quot;application/vnd.visio&quot;},
	 *             {&quot;vtx&quot;,&quot;application/vnd.visio&quot;},
	 *             {&quot;wav&quot;,&quot;audio/wav&quot;},
	 *             {&quot;wave&quot;,&quot;audio/wav&quot;},
	 *             {&quot;wax&quot;,&quot;audio/x-ms-wax&quot;},
	 *             {&quot;wbk&quot;,&quot;application/msword&quot;},
	 *             {&quot;wbmp&quot;,&quot;image/vnd.wap.wbmp&quot;},
	 *             {&quot;wcm&quot;,&quot;application/vnd.ms-works&quot;},
	 *             {&quot;wdb&quot;,&quot;application/vnd.ms-works&quot;},
	 *             {&quot;wdp&quot;,&quot;image/vnd.ms-photo&quot;},
	 *             {&quot;webarchive&quot;,&quot;application/x-safari-webarchive&quot;},
	 *             {&quot;webtest&quot;,&quot;application/xml&quot;},
	 *             {&quot;wiq&quot;,&quot;application/xml&quot;},
	 *             {&quot;wiz&quot;,&quot;application/msword&quot;},
	 *             {&quot;wks&quot;,&quot;application/vnd.ms-works&quot;},
	 *             {&quot;wlmp&quot;,&quot;application/wlmoviemaker&quot;},
	 *             {&quot;wlpginstall&quot;,&quot;application/x-wlpg-detect&quot;},
	 *             {&quot;wlpginstall3&quot;,&quot;application/x-wlpg3-detect&quot;},
	 *             {&quot;wm&quot;,&quot;video/x-ms-wm&quot;},
	 *             {&quot;wma&quot;,&quot;audio/x-ms-wma&quot;},
	 *             {&quot;wmd&quot;,&quot;application/x-ms-wmd&quot;},
	 *             {&quot;wmf&quot;,&quot;application/x-msmetafile&quot;},
	 *             {&quot;wml&quot;,&quot;text/vnd.wap.wml&quot;},
	 *             {&quot;wmlc&quot;,&quot;application/vnd.wap.wmlc&quot;},
	 *             {&quot;wmls&quot;,&quot;text/vnd.wap.wmlscript&quot;},
	 *             {&quot;wmlsc&quot;,&quot;application/vnd.wap.wmlscriptc&quot;},
	 *             {&quot;wmp&quot;,&quot;video/x-ms-wmp&quot;},
	 *             {&quot;wmv&quot;,&quot;video/x-ms-wmv&quot;},
	 *             {&quot;wmx&quot;,&quot;video/x-ms-wmx&quot;},
	 *             {&quot;wmz&quot;,&quot;application/x-ms-wmz&quot;},
	 *             {&quot;wpl&quot;,&quot;application/vnd.ms-wpl&quot;},
	 *             {&quot;wps&quot;,&quot;application/vnd.ms-works&quot;},
	 *             {&quot;wri&quot;,&quot;application/x-mswrite&quot;},
	 *             {&quot;wrl&quot;,&quot;x-world/x-vrml&quot;},
	 *             {&quot;wrz&quot;,&quot;x-world/x-vrml&quot;},
	 *             {&quot;wsc&quot;,&quot;text/scriptlet&quot;},
	 *             {&quot;wsdl&quot;,&quot;text/xml&quot;},
	 *             {&quot;wvx&quot;,&quot;video/x-ms-wvx&quot;},
	 *             {&quot;x&quot;,&quot;application/directx&quot;},
	 *             {&quot;xaf&quot;,&quot;x-world/x-vrml&quot;},
	 *             {&quot;xaml&quot;,&quot;application/xaml+xml&quot;},
	 *             {&quot;xap&quot;,&quot;application/x-silverlight-app&quot;},
	 *             {&quot;xbap&quot;,&quot;application/x-ms-xbap&quot;},
	 *             {&quot;xbm&quot;,&quot;image/x-xbitmap&quot;},
	 *             {&quot;xdr&quot;,&quot;text/plain&quot;},
	 *             {&quot;xht&quot;,&quot;application/xhtml+xml&quot;},
	 *             {&quot;xhtml&quot;,&quot;application/xhtml+xml&quot;},
	 *             {&quot;xla&quot;,&quot;application/vnd.ms-excel&quot;},
	 *             {&quot;xlam&quot;,&quot;application/vnd.ms-excel.addin.macroenabled.12&quot;},
	 *             {&quot;xlc&quot;,&quot;application/vnd.ms-excel&quot;},
	 *             {&quot;xld&quot;,&quot;application/vnd.ms-excel&quot;},
	 *             {&quot;xlk&quot;,&quot;application/vnd.ms-excel&quot;},
	 *             {&quot;xll&quot;,&quot;application/vnd.ms-excel&quot;},
	 *             {&quot;xlm&quot;,&quot;application/vnd.ms-excel&quot;},
	 *             {&quot;xls&quot;,&quot;application/vnd.ms-excel&quot;},
	 *             {&quot;xlsb&quot;,&quot;application/vnd.ms-excel.sheet.binary.macroenabled.12&quot;},
	 *             {&quot;xlsm&quot;,&quot;application/vnd.ms-excel.sheet.macroenabled.12&quot;},
	 *             {&quot;xlsx&quot;,&quot;application/vnd.openxmlformats-officedocument.spreadsheetml.sheet&quot;},
	 *             {&quot;xlt&quot;,&quot;application/vnd.ms-excel&quot;},
	 *             {&quot;xltm&quot;,&quot;application/vnd.ms-excel.template.macroenabled.12&quot;},
	 *             {&quot;xltx&quot;,&quot;application/vnd.openxmlformats-officedocument.spreadsheetml.template&quot;},
	 *             {&quot;xlw&quot;,&quot;application/vnd.ms-excel&quot;},
	 *             {&quot;xml&quot;,&quot;text/xml&quot;},
	 *             {&quot;xmta&quot;,&quot;application/xml&quot;},
	 *             {&quot;xof&quot;,&quot;x-world/x-vrml&quot;},
	 *             {&quot;xoml&quot;,&quot;text/plain&quot;},
	 *             {&quot;xpm&quot;,&quot;image/x-xpixmap&quot;},
	 *             {&quot;xps&quot;,&quot;application/vnd.ms-xpsdocument&quot;},
	 *             {&quot;xrm-ms&quot;,&quot;text/xml&quot;},
	 *             {&quot;xsc&quot;,&quot;application/xml&quot;},
	 *             {&quot;xsd&quot;,&quot;text/xml&quot;},
	 *             {&quot;xsf&quot;,&quot;text/xml&quot;},
	 *             {&quot;xsl&quot;,&quot;text/xml&quot;},
	 *             {&quot;xslt&quot;,&quot;text/xml&quot;},
	 *             {&quot;xsn&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;xss&quot;,&quot;application/xml&quot;},
	 *             {&quot;xtp&quot;,&quot;application/octet-stream&quot;},
	 *             {&quot;xwd&quot;,&quot;image/x-xwindowdump&quot;},
	 *             {&quot;z&quot;,&quot;application/x-compress&quot;},
	 *             {&quot;zip&quot;,&quot;application/x-zip-compressed&quot;}}
	 *
	 * @var string
	 */
	public $customAllowedFileExtensions = null;


}

